name: 'testaction'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - run: |
        echo "test action..." 
        echo "x" >> xfile
        git -c user.name=tuf-on-ci -c user.email=41898282+github-actions[bot]@users.noreply.github.com add xfile
        git -c user.name=tuf-on-ci -c user.email=41898282+github-actions[bot]@users.noreply.github.com commit -a -m "xfile change"
        git push origin main        
      shell: bash
