name: test workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./testaction
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN }}
