name: test workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./testaction
